services:
  - type: web
    name: screen-streamer
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    autoDeploy: true
    plan: free
